name: Report a bug
description: Tell us about a bug or issue you may have identified in the form validation library.
title: "Provide a general summary of the issue"
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched](https://github.com/ltvco/form-validation/issues?q=is%3Aissue%20state%3Aopen%20label%3Abug) for duplicate or closed issues
          required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Tell us how we can recreate the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What operating system(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Opera
        - Other
    validations:
      required: true
  - type: input
    id: other-browser
    attributes:
      label: Other browser(s)
      description: If your browser isn't listed above, type it here.
      placeholder: e.g. Brave, Vivaldi, etc.
  - type: input
    id: browser-version
    attributes:
      label: What version of the browser are you using?
      placeholder: "e.g., Chrome 124.0.6367.91 or Safari 17.5"
    validations:
      required: true
  - type: textarea
    id: form-setup
    attributes:
      label: Form setup and validation rules
      description: Please provide details about your form setup, validation rules, and any relevant HTML/JavaScript code.
      placeholder: |
        Example:
        ```html
        <form id="myForm">
          <input type="email" name="email" required>
        </form>
        ```
        ```js
        const validator = new FormValidator('#myForm', {
          rules: { email: 'required|email' }
        });
        ```
    validations:
      required: false
